### ISSUE TITLE
store_baseline_file_branch flag overwrites the README.md file

### ISSUE THREAD

**Issue by mouradzadegun** [veracode/Veracode-pipeline-scan-action#8]
## Issue Description
When `store_baseline_file_branch` is set to 'true', the action will update the results.json file within in that specified branch. However, along side `results.json` the Veracode pipeline scanner's `README.md` file is also committed to the repository.

## Screenshots
<img width="1509" alt="Screenshot 2023-07-06 at 8 10 44 PM" src="https://github.com/veracode/Veracode-pipeline-scan-action/assets/57601790/a38cdc1f-738a-40c7-befa-2642f35ef49d">

## Issue Source
I suspect the issue is stemmed from [pipeline-scan.ts](https://github.com/veracode/Veracode-pipeline-scan-action/blob/master/src/pipeline-scan.ts#L23) file, where everything within `pipeline-scan-LATEST.zip` is unzipped in the current directory.

Since README.md is tracked file within our repository, it will be overwritten with this method in [commit.ts](https://github.com/veracode/Veracode-pipeline-scan-action/blob/master/src/commit.ts#L48-L55).

## Possible fix
Restrict `git stash` command to individual file. Example: `git stash push -- ${baselineFileName}`. This will only stash one file and similarly when checking out the stash we can restrict that baseline file as well: `git checkout stash -- ${baselineFileName}`

**Comment by julz0815** [comment]
Hi @mouradzadegun, we have completely overlooked your request from last year! We are very sorry for not answering on time. The required updates are now implemented with the latest version of the action v1.0.11. Please give it a try and let us know if it works as expected now.

**Comment by mouradzadegun** [comment]
Hi @julz0815, I can confirm I tested the new version it does work as expected. Thank you for resolving this issue.
